//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.16.0
//     from Assets/xilogravuraStuff/Scripts/Inputs/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/xilogravuraStuff/Scripts/Inputs/Input.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Input: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""ControlesDebug"",
            ""id"": ""6f0ff355-5bf5-4def-a7b4-3802fd0bd52d"",
            ""actions"": [
                {
                    ""name"": ""DecreaseBrush"",
                    ""type"": ""Button"",
                    ""id"": ""f348829e-af4c-4b81-882c-675d5362cc33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseBrush"",
                    ""type"": ""Button"",
                    ""id"": ""2dbc6787-9231-47be-a45f-d4a43bd23d9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eventos"",
                    ""type"": ""Value"",
                    ""id"": ""d71305fb-d3b6-49f7-b83e-bc83572dd907"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""66a8508e-b6e9-4f10-ade2-91e2e7f6367d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseBrush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7682fc9-ad23-4a1e-b421-dc6869fc232e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseBrush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b94df013-8658-4b67-ab86-21ec5619d5af"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseBrush"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ControlesDebug
        m_ControlesDebug = asset.FindActionMap("ControlesDebug", throwIfNotFound: true);
        m_ControlesDebug_DecreaseBrush = m_ControlesDebug.FindAction("DecreaseBrush", throwIfNotFound: true);
        m_ControlesDebug_IncreaseBrush = m_ControlesDebug.FindAction("IncreaseBrush", throwIfNotFound: true);
        m_ControlesDebug_Eventos = m_ControlesDebug.FindAction("Eventos", throwIfNotFound: true);
    }

    ~@Input()
    {
        UnityEngine.Debug.Assert(!m_ControlesDebug.enabled, "This will cause a leak and performance issues, Input.ControlesDebug.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlesDebug
    private readonly InputActionMap m_ControlesDebug;
    private List<IControlesDebugActions> m_ControlesDebugActionsCallbackInterfaces = new List<IControlesDebugActions>();
    private readonly InputAction m_ControlesDebug_DecreaseBrush;
    private readonly InputAction m_ControlesDebug_IncreaseBrush;
    private readonly InputAction m_ControlesDebug_Eventos;
    /// <summary>
    /// Provides access to input actions defined in input action map "ControlesDebug".
    /// </summary>
    public struct ControlesDebugActions
    {
        private @Input m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ControlesDebugActions(@Input wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ControlesDebug/DecreaseBrush".
        /// </summary>
        public InputAction @DecreaseBrush => m_Wrapper.m_ControlesDebug_DecreaseBrush;
        /// <summary>
        /// Provides access to the underlying input action "ControlesDebug/IncreaseBrush".
        /// </summary>
        public InputAction @IncreaseBrush => m_Wrapper.m_ControlesDebug_IncreaseBrush;
        /// <summary>
        /// Provides access to the underlying input action "ControlesDebug/Eventos".
        /// </summary>
        public InputAction @Eventos => m_Wrapper.m_ControlesDebug_Eventos;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ControlesDebug; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ControlesDebugActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ControlesDebugActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ControlesDebugActions" />
        public void AddCallbacks(IControlesDebugActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlesDebugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlesDebugActionsCallbackInterfaces.Add(instance);
            @DecreaseBrush.started += instance.OnDecreaseBrush;
            @DecreaseBrush.performed += instance.OnDecreaseBrush;
            @DecreaseBrush.canceled += instance.OnDecreaseBrush;
            @IncreaseBrush.started += instance.OnIncreaseBrush;
            @IncreaseBrush.performed += instance.OnIncreaseBrush;
            @IncreaseBrush.canceled += instance.OnIncreaseBrush;
            @Eventos.started += instance.OnEventos;
            @Eventos.performed += instance.OnEventos;
            @Eventos.canceled += instance.OnEventos;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ControlesDebugActions" />
        private void UnregisterCallbacks(IControlesDebugActions instance)
        {
            @DecreaseBrush.started -= instance.OnDecreaseBrush;
            @DecreaseBrush.performed -= instance.OnDecreaseBrush;
            @DecreaseBrush.canceled -= instance.OnDecreaseBrush;
            @IncreaseBrush.started -= instance.OnIncreaseBrush;
            @IncreaseBrush.performed -= instance.OnIncreaseBrush;
            @IncreaseBrush.canceled -= instance.OnIncreaseBrush;
            @Eventos.started -= instance.OnEventos;
            @Eventos.performed -= instance.OnEventos;
            @Eventos.canceled -= instance.OnEventos;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ControlesDebugActions.UnregisterCallbacks(IControlesDebugActions)" />.
        /// </summary>
        /// <seealso cref="ControlesDebugActions.UnregisterCallbacks(IControlesDebugActions)" />
        public void RemoveCallbacks(IControlesDebugActions instance)
        {
            if (m_Wrapper.m_ControlesDebugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ControlesDebugActions.AddCallbacks(IControlesDebugActions)" />
        /// <seealso cref="ControlesDebugActions.RemoveCallbacks(IControlesDebugActions)" />
        /// <seealso cref="ControlesDebugActions.UnregisterCallbacks(IControlesDebugActions)" />
        public void SetCallbacks(IControlesDebugActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlesDebugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlesDebugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ControlesDebugActions" /> instance referencing this action map.
    /// </summary>
    public ControlesDebugActions @ControlesDebug => new ControlesDebugActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ControlesDebug" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ControlesDebugActions.AddCallbacks(IControlesDebugActions)" />
    /// <seealso cref="ControlesDebugActions.RemoveCallbacks(IControlesDebugActions)" />
    public interface IControlesDebugActions
    {
        /// <summary>
        /// Method invoked when associated input action "DecreaseBrush" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDecreaseBrush(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IncreaseBrush" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIncreaseBrush(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Eventos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEventos(InputAction.CallbackContext context);
    }
}
